{{- if .Values.ingress.enabled -}}
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: add-trailing-slash
  namespace: default
spec:
  redirectRegex:
    regex: "^(https?://[^/]+/[^/]+)$"
    replacement: "${1}/"
    permanent: false
{{- end }}
